### ISSUE TITLE
child_process.spawn ignores PATHEXT on Windows

### ISSUE THREAD

**Issue by OrangeDog** [nodejs/node-v0.x-archive#2318]
For example `require('child.process').spawn('mycmd')` won't find `C:\util\mycmd.bat` when PATH contains `C:\util` and PATHEXT contains `.BAT`.

Ye olde code (https://github.com/joyent/node/blob/v0.4/src/node_child_process_win32.cc) looks like it would have worked, but I have no idea where the v0.6 equivalent is.

**Comment by steelbrain** [comment]
It's been years and this is still a bug, has it been fixed in io.js btw?

**Comment by alexturpin** [comment]
Just reiterating that this issue is still well and alive.

**Comment by killanaca** [comment]
hi, any news?

**Comment by jasnell** [comment]
@orangemocha ... would you have an opportunity to look at this one?

**Comment by orangemocha** [comment]
Yes, it's on my queue and I am aware of its importance.

**Comment by jasnell** [comment]
Ok. Just checking in :)

**Comment by ghost** [comment]
Is this ever going to be fixed in v0.12.x or just in the latest version?

**Comment by jasnell** [comment]
@waynebloss ... unclear. hopefully this one will get done for v0.12 but it's going to depend entirely on @orangemocha's availability to take a look... unless someone else is able to step up and help resolve it.

**Comment by nyarasha** [comment]
Any update on this bugfix? Just ran into it today and am going to have to do some hacky things to get this to work with Windows.

**Comment by AddoSolutions** [comment]
In my case, I tried to package what is basically the boilerplate package, and whenever I removed the `--icon-icon.ico` flag, I stopped getting this error.  Not sure if that is of any value to debugging this issue.

**Comment by UltCombo** [comment]
Is this fixed by https://github.com/nodejs/node/pull/4598 ?

**Comment by tjwebb** [comment]
+1. I have to do this to run Windows binaries that do not end in `.exe`:

``` js
if (/win/.test(os.platform())) {
  command += ".cmd"
}
spawn(command, [ ... ])
```

**Comment by addaleax** [comment]
Does this still occur with current versions of Node.js? I don’t think there’s an open issue for this in the active repository at https://github.com/nodejs/node/issues. So either this has been fixed, or you may want to report it there, this repo here is no longer in use.

**Comment by timdp** [comment]
@tjwebb That won't work with `.bat` or anything else in `PATHEXT`. The most reliable solution is to use [cross-spawn](https://www.npmjs.com/package/cross-spawn).

**Comment by cancerberoSgx** [comment]
+1  IMO this is an issue. If you can install something globally with npm then you should be able to execute it using spawn() in any OS. In my case I have to execute 'node node_modules/gulp/bin/gulp' instead of just 'gulp' - this is ugly in my integration tests that need to be run in windows....

**Comment by flyskywhy** [comment]
This issue was resolved elegantly by https://github.com/adriaanthomas/npm-pkgr/commit/46631850455e6453bdfeb0d06fd59721c8cfb8f6 , @adriaanthomas :+1: 

e.g. npm, just replace

```
spawn('npm', ...
```

by

```
spawn(/^win/.test(process.platform) ? 'npm.cmd' : 'npm', ...
```

**Comment by UltCombo** [comment]
@flyskywhy That's not actually a "fix", it is an ugly workaround in userland code that should be completely unnecessary if this Node.js issue was actually fixed.

In any case, as several people have explained, this issue is due to OS discrepancies in how they handle shell commands and executable files. I believe the closest thing to a real fix is the recently introduced `child_process.spawn()`'s `shell` option, as documented [here](https://nodejs.org/api/child_process.html#child_process_spawning_bat_and_cmd_files_on_windows). If this issue tracker is still maintained, I believe this issue can be closed.

**Comment by flyskywhy** [comment]
@UltCombo , OK, for short :smile: :

e.g. replace spawn('npm', ['-v'], {stdio: 'inherit'}) with:
- for all node.js version:
  
  ```
  spawn(/^win/.test(process.platform) ? 'npm.cmd' : 'npm', ['-v'], {stdio: 'inherit'})
  ```
- for node.js 5.x and later:
  
  ```
  spawn('npm', ['-v'], {stdio: 'inherit', shell: true})
  ```

**Comment by UltCombo** [comment]
👍

By the way, I believe you can test `process.platform === 'win32'` without a regexp; The 64 bits versions of Windows are still part of the `win32` platform, "64 bits" is just an extension of win32.

**Comment by flyskywhy** [comment]
@UltCombo , I just learn this regexp from https://github.com/facebook/react-native/commit/811079ede2dd32bca4b5891ea42c27dbdb488da0 which also trying to solve such `spawn('npm'...` ENOENT problem :stuck_out_tongue_winking_eye:

**Comment by bzoz** [comment]
Is this still an issue? Does adding `{shell:true}` fixes it?

**Comment by deltreey** [comment]
@bzoz I expressed this as 5 separate issues here https://github.com/nodejs/node-v0.x-archive/issues/2318#issuecomment-44227527 so we might use those as tests cases if we wanted to know if `{shell: true}` fixes it.

**Comment by bzoz** [comment]
I did testing with current node, and:

- ["spawn not using PATHEXT"](https://github.com/nodejs/node-v0.x-archive/issues/2318#issuecomment-7470062) (the issue that started this) is fixed by adding `{shell: true}`
- ["weird escape issues"](https://github.com/nodejs/node-v0.x-archive/issues/2318#issuecomment-34877743) is somewhat fixed by adding `{shell: true}`. It uses `cmd /c /s` which handles escaping little better. There are still some quirks, but this looks like it is the best we can do as described here: https://github.com/nodejs/node/issues/7367#issuecomment-238594729
- ["spawn doesn't execute non-executables"](https://github.com/nodejs/node-v0.x-archive/issues/2318#issuecomment-3219836) is also fixed by adding `{shell: true}`
- As for ["spawn can potentially orphan grandchildren"](https://github.com/nodejs/node-v0.x-archive/issues/2318#issuecomment-10549609) and ["additional features"](https://github.com/nodejs/node-v0.x-archive/issues/2318#issuecomment-7462307) - those are valid concerns, related to this issue, but should have their own separate issue opened. 

I think we should close this issue and maybe have new ones opened for the remaining two items (grandchildren and additional features)

**Comment by bzoz** [comment]
I'm closing this issue. You can always reopen it if needed.

**Comment by satazor** [comment]
@bzoz when using shell:true you must escape everything manually, nodejs just joins the args and wraps them with quotes.

You should correct your comment because it misleads people into thinking escaping is done inside which isn't true.
