### ISSUE TITLE
Issue with cyrillic symbols in location headers

### ISSUE THREAD

**Issue by LavrovArtem** [nodejs/node-v0.x-archive#25293]
To reproduce this bug, execute the code below and open http://localhost:777/ in the browser. This page redirects to a page from the location header, and browser should open http://localhost:777/?text=что-то%20русское .

In node.js version 0.10.15 and earlier, it works fine, but in the latest version, node.js opens the http://localhost:777/?text=GB>-B>%20@CAA:>5 url.

I think that the issue is linked to the writeHead function that incorrectly encodes headers and sends them to the browser.

    var http = require('http');

    http.createServer(function(req, res) {
        if (req.url === '/')
            res.writeHead(302, {location:'?text=что-то русское'});

        res.end();
    }).listen(777);

**Comment by dnakamura** [comment]
Seems to be an issue introduced with 6d3d60a . Workarround:
```
var http = require('http');

http.createServer(function(req, res) {
    if (req.url === '/')
        res.writeHead(302, {location:'?text=что-то русское'});

    res.end('', 'utf-8');
}).listen(777);
```

**Comment by ChALkeR** [comment]
Cross-linking: https://github.com/iojs/io.js/issues/1693

**Comment by jasnell** [comment]
Confirmed. There are workarounds for this documented in https://github.com/iojs/io.js/issues/1693, and developers really ought not be passing non-ascii characters into the headers but `writeHead` should be operating defensively here and it's not. This ought to get fixed but since there are good workarounds it's likely not a high priority.

Node versions affected: Tested on v0.12.2
Platforms affected: Tested on mac, should apply to all platforms
High priority/critical category: No
recommended priority: P3
Existing io.js issue: https://github.com/iojs/io.js/issues/1693
Pull request included: No
Reproducible: Yes
Exists in later version: Not yet tested in v0.10
@joyent/node-coreteam

**Comment by ChALkeR** [comment]
This is the same issue as https://github.com/nodejs/node/issues/1693.
No reason to keep a dupe open in the archive, the discussion should move to `nodejs/node`.
