### ISSUE TITLE
Error 2908 when updating node in Windows XP

### ISSUE THREAD

**Issue by deliverymanager** [nodejs/node-v0.x-archive#25370]
An issue that I have seen when trying to upgrade node (using msi file) in Windows XP machines, no matter which version was already installed in the machine, is that I get an error 2908 during the installation process.
I have done a lot of research and found out that this error is related to the registry.
So this issue is resolved by doing a defragment of the registry with an external software.

But I am really curious why this happens when I try to upgrade to a newer version.
Most installation packages probably handle this defragment internally, so that the user will not have to make the registry defragment externally.

Also, the same error appears if I first uninstall the already installed node version and then install the new version. The error 2908 still appears when installing.

This is issue is only related with Windows XP and I have never seen it in other Windows version for example windows 7 that I have tested many times.

**Comment by misterdjules** [comment]
@deliverymanager Is this a recent regression, or has it been like this for a while?

**Comment by deliverymanager** [comment]
This has always been an issue. At least from 0.10.33 that I started installing node in Windows XP machines. So it is not related to any recent version.

**Comment by deliverymanager** [comment]
I want to emphasise that the error 2908 appears during the upgrading/installation process only!
And only if node was previously installed in the Windows XP machine.

**Comment by nirmalksamuel** [comment]
I came in here to report this bug, as a thank you note to all the developers who work on node.js.  Today i tried to install the 4.x stable version on a Windows XP machine and saw this error. I am attaching a screenshot herewith.  The only thing i could think of at that time was that I was running the  _node.js  Command Prompt_  from the prior version during the installation.  I don't recall the exact version number of prior installation,  but i am sure it was 0.x.x  which i installed during summer 2014.  I closed that Command Prompt window and retried installation, which went through fine this time.  But, i am not sure if that is because the prior installation attempt _did not clean up_
 registry entries  (I had to use _Windows Task Manager_ to kill the installation process, which was stuck in an infinite loop of showing that error box you see in the attached image).

![node-install](https://cloud.githubusercontent.com/assets/7623186/11107805/03a32646-8896-11e5-95bc-76569dfc870e.png)

**Comment by deliverymanager** [comment]
Yes  the error still appears only on Windows XP when updating.
The solution that I came up with.
1. Uninstall all the versions of node.
2. Install a software that will make registry defragment. If you dont find any let me know.
3. Restart your computer and now the installation process will procees.
