### ISSUE TITLE
path.join with disk gives corrupt path

### ISSUE THREAD

**Issue by ganna-shmatova** [nodejs/node-v0.x-archive#25479]
node version 0.12.4

``` js
var folders = dir.split(path.sep);

var counter = 0;
var cursor = '';
function ensureNext(){
    if(counter < folders.length){
        cursor = path.join(cursor, folders[counter]);
        console.log(cursor);
        fs.exists(cursor, function(exists){
            if(exists){
                ensureNext();
            }else{
                console.log('makes ' + cursor);
                fs.mkdir(cursor, function(err){
                    if(err)
                        log.warn(err);
                    ensureNext();
                });
            }
        });
    }else if(counter === folders.length){
        if(cb) cb();
    }
    counter++;
}
ensureNext();
```

```
C:.
C:Users
makes C:Users
C:Users\Ganna
makes C:Users\Ganna
C:Users\Ganna\git
makes C:Users\Ganna\git
```

so `path.join('', 'C:')` becomes `C:.` ???
and `path.join('C:.', 'Users')` is missing a `\`

(when it mkdir it seems to ignore everything until after the : character, so I was having the whole folder hierarchy being remade as relative)

**Comment by dnakamura** [comment]
Yeah, the problem stems from the fact that path.join does not recognize "c:" as an absolute path.
As a workaround for the moment you can replace 
``` cursor = path.join(cursor, folders[counter]); ```
 with
``` cursor = path.join(cursor, folders[counter] + path.sep); ```

**Comment by ganna-shmatova** [comment]
initially I made this ticket thinking it did not recognize `C:`, but it does...

`path.join('C:', 'Users')` works correctly and returns `C:/Users`.

turns out the problem was `path.join('', 'C:')` = `C.`
it adds a dot character after `C:`, and that seems to mess things up when you try joining again.

---

my workaround was
```js
if(cursor.length>0)
	cursor = path.join(cursor, folders[counter]);
else
	cursor = folders[counter];
```

**Comment by mhdawson** [comment]
Talking with @dnakamura, it sounds like the existing code requires a trailing '\' after 'C:' to recongnize it as an absolute path, otherwise it treats it as relative.  It only seems like its only an issue if the result will end with a ":", for example when you try to concat an empty string with 'c:'.  It would be straight forward to change so that the result would end up including the slash. for example  path.join('', 'C:') would end up being "C:\".  Since it already adds the . then maybe adding the '\' would also make sense. 

@orangemocha does it make sense to change it to work that way ?

**Comment by manikawnth** [comment]
This is not the right way in windows. In Windows every partition itself will have a root directory.
So if your process is running from C drive, / will point C:\ and if it is from D drive, / will point to D:\
So if you want to resolve for each drive, you need to give first partition, then root, then path.
console.log(path.join('C','/'))            ==> C\   (since it is string joining)
console.log(path.resolve('C','/'))            ==> C:\   (since it resolves path)

**Comment by orangemocha** [comment]
So, in `path.join('', 'C:')` the empty string is simply ignored, and so this call is equivalent to `path.normalize('C:')`.

`path.normalize('C:')` returns `'C:.'`, which doesn't make a whole lot of sense. I think it should just return `'C:'`

**Comment by ganna-shmatova** [comment]
^ +1 yess!

**Comment by orangemocha** [comment]
It is also somewhat questionable that `path.join('C:', 'root')` returns `'C:\root'`. I would expect it to return `'C:root'`, as .NET's [Path.Combine](https://msdn.microsoft.com/en-us/library/fyy7a5kt(v=vs.110).aspx) does.
