### ISSUE TITLE
.load results in hang when allocating Int8Array to predeclared var

### ISSUE THREAD

**Issue by johansen** [nodejs/node-v0.x-archive#25532]
(I originally [asked](http://stackoverflow.com/questions/30336024/why-does-node-sometimes-hang-when-allocating-int8array) about this on StackExchange and was told I should file a bug report.)

Consider the following two programs:

```
// works.js
var buffer = new ArrayBuffer(16777216);
var HEAP8 = new Int8Array(buffer);
```

and

```
// fails.js
var HEAP8;
var buffer = new ArrayBuffer(16777216);
HEAP8 = new Int8Array(buffer);
```

Run `node` then enter `.load works.js`. Everything seems happy. Now exit `node`.

Run `node` again and enter `.load fails.js`.

On my machine loading `fails.js` interactively leads the `node` process to consume over 1GB of RAM and 100% CPU, and the final statement blocks the interpreter forever. `works.js` just runs and returns as expected.

Curiously enough, running either script directly from the command line works fine:

```
node works.js    # exits normally
node fails.js    # exits normally
```

I'm using node 0.12.0 on OS X 10.9.5

**Comment by jasnell** [comment]
Could you please try the same test using the latest io.js?

**Comment by cjihrig** [comment]
This reproduces for me on the latest io.js. I haven't dug into it too much, but the problem appears to be a result of trying to print the large `Int8Array()`. You don't see the crash with `works.js` or when running the script from the command line because you aren't printing `HEAP8`. The following simplified example shows this. Notice that `foo` is not printed because it is part of variable declaration, but `bar` is printed after the assignment statement. If you call `util.inspect()` on `HEAP8` in `works.js` when run from the command line, you'll see the same crash.

```
> var foo = 5;
undefined
> var bar;
undefined
> bar = 10;
10
```

**Comment by jasnell** [comment]
@cjihrig .. ah, yeah, good point. I hadn't given it any significant thought ;-) .. but printing that buffer could definitely cause a spike like that.
