### ISSUE TITLE
path.resolve / fs.readdir for UNC path problem

### ISSUE THREAD

**Issue by felixpis** [nodejs/node-v0.x-archive#25552]
I have a folder on network computer: \\COMPUTE-NAME\public. When executing:
path.resolve('\\\\COPUTER-NAME\\public') or path.resolve('//COMPUTER-NAME/public') I'm getting
\\COMPUTE-NAME\public and it's ok. But path.resolve('\\\\COMPUTER-NAME\\') gives the result:
C:\COMPUTER-NAME (I want to get list of shared folders on specific computer in my domain)

**Comment by dnakamura** [comment]
What version are you running? Also 32 or 64bit (although I suspect it doesn't matter)

**Comment by robmcl4** [comment]
I observe the following on v0.12.2 64bit, Windows 8.1

```javascript
> var path = require('path')
undefined
> path.resolve('\\\\FOO-BAR\\')
'C:\\FOO-BAR'
> path.resolve('\\\\FOO-BAR\\public')
'\\\\FOO-BAR\\public\\'
> exit
```

@joyland can you confirm the following

Expected Behavior:
```javascript
> path.resolve('\\\\FOO-BAR\\')
'\\\\FOO-BAR\\'
```
Actual Behavior
```javascript
> path.resolve('\\\\FOO-BAR\\')
'C:\\FOO-BAR'
```

**Comment by joyland** [comment]
Hi
Yes, that is what expected in my opinion. If not, perhaps there is another option to read folders from shared computer?
Thanks, 
Felix 

-----Исходное сообщение-----
От: "Robert McLaughlin" <notifications@github.com>
Отправлено: ‎25.‎06.‎2015 5:41
Кому: "joyent/node" <node@noreply.github.com>
Копия: "joyland" <felix.piskunov@gmail.com>
Тема: Re: [node] path.resolve / fs.readdir for UNC path problem (#25552)

I observe the following on v0.12.2 64bit, Windows 8.1
> var path = require('path')
undefined
> path.resolve('\\\\FOO-BAR\\')
'C:\\FOO-BAR'
> path.resolve('\\\\FOO-BAR\\public')
'\\\\FOO-BAR\\public\\'
> exit@joyland can you confirm the following
Expected Behavior:
> path.resolve('\\\\FOO-BAR\\')
'\\\\FOO-BAR\\'Actual Behavior
> path.resolve('\\\\FOO-BAR\\')
'C:\\FOO-BAR'—

**Comment by dnakamura** [comment]
As it turns out according to the [Microsoft docs](https://msdn.microsoft.com/en-us/library/gg465305.aspx) \\\\COMPUTERNAME\\ is not a valid UNC path, it must always have a share name as well. Also, doing just a directory listing on \\COMPUTER-NAME\ [will fail](http://stackoverflow.com/questions/2091126/enumerating-network-shares-with-c-sharp). There is a specific windows api call ([NetShareEnum](https://msdn.microsoft.com/en-us/library/windows/desktop/bb525387%28v=vs.85%29.aspx)) for that, however I don't think that there is currently any way to get from it from the node level.

**Comment by joyland** [comment]
Thanks for response!
