### ISSUE TITLE
Clarify access error for Cannot find module on absolute paths

### ISSUE THREAD

**Issue by GeorgeBailey** [nodejs/node-v0.x-archive#25585]
The `Error: Cannot find module: '/path/to/module.node.js'` would ideally show the original error from `fs.statSync` (i.e. `EACCES`). This prevents confusion when someone says - but this file exists?? Said feature would apply only to absolute paths `/` or `./` or `../`.

(Relative paths search `module.paths`, and silently skipping access errors is a matter of course, so the existing message is fine then.)

If you agree this is an OK feature to include, I'll write a good implementation and provide a pull request. The changes would be in `module.js` only, and would have minimal impact to the performance of non-error loading of modules.

**Comment by jasnell** [comment]
@GeorgeBailey ... the best place to target such a PR at this time would be nodejs/io.js. Assuming it lands there, it would be picked up in the converged stream.

**Comment by GeorgeBailey** [comment]
@jasnell, As you might expect, I have only limited information on the relationship between io.js and Node.js.

Can you clarify what is meant by converged stream? Supposing my PR is accepted into io.js, how likely is it to be accepted into an upcoming Node.js release?

**Comment by jasnell** [comment]
@GeorgeBailey ... node.js and io.js are in the process of converging back into a single project stream. The joyent/node repository contains the node v0.10 and v0.12 long term support branches. Those will be merged with the nodejs/io.js repository very soon. Because of this process, new features (even relatively simple ones like modifying how errors are reported) should go into future releases as opposed to the LTS releases.
