### ISSUE TITLE
fs.writeFile and fs.writeFileSync ignores options.mode and always writes with permission '644'

### ISSUE THREAD

**Issue by kaizhu256** [nodejs/node-v0.x-archive#25756]
bug reproduced on node v0.10 and v0.12, on both linux and mac with the following code:

var fs = require('fs');
fs.writeFileSync('a00.txt', 'hello', { mode: '666' });
console.log(fs.statSync('a00.txt').mode.toString(8));
// output: 100644

**Comment by thefourtheye** [comment]
Just tried with v0.12.7 and I got `100666`

**Comment by kaizhu256** [comment]
![image](https://cloud.githubusercontent.com/assets/280571/8849524/f7db57ae-3172-11e5-9c07-3049ff28fb54.png)

here's screenshot on my macbook air (late 2014, running mavericks with homebrew node v0.12.7)

**Comment by kaizhu256** [comment]
another screenshot running debian unstable on linode

![image](https://cloud.githubusercontent.com/assets/280571/8849567/613325d8-3173-11e5-8d49-50b0134734a8.png)

**Comment by jfmercer** [comment]
I've gotten some strange results. It works when I use `'0755'`, but not when I use `'0666'`. Because octals are forbidden in strict mode, I've passed them as strings to `parseInt()`. 

`'0755'`: 

![image](https://cloud.githubusercontent.com/assets/590520/8856843/57a74c8e-313b-11e5-9e14-d299b63d3099.png)

`'0666'`: 

![image](https://cloud.githubusercontent.com/assets/590520/8856895/a2a4cb6c-313b-11e5-8967-17315fbe59f1.png)

**Comment by targos** [comment]
I can reproduce the results in the OP with v0.12.7. (OSX 10.10)

**Comment by jasnell** [comment]
Yes, I'm able to reproduce this. The documentation even states that the default mode is 666, but when calling writeFileSync without the mode param, the mode will still be set as 644. /cc @joyent/node-tsc

**Comment by jfmercer** [comment]
My workaround was to use `fs.chmod`, e.g., `fs.chmod('file.txt', '0755');`, after the file had been created with `fs.writeFile`. Note that I had to pass the octal number as a string because JS strict mode prohibits the use of octal numbers, but not parsable octal strings. 

Still, I'd like `fs.writeFile` and `fs.writeFileSync` work as described in the documentation.

**Comment by targos** [comment]
I found that this is in fact not an issue, but just how UNIX file permissions are handled.
Whatever mode you pass to writeFile, it will be combined with the [umask](https://en.wikipedia.org/wiki/Umask) during the `open` system call.

You can change the umask with [`process.umask(newValue)`](https://nodejs.org/api/process.html#process_process_umask_mask). If you set it to 0, the mode will be set exactly to the value you pass to the `fs` methods.

See https://github.com/nodejs/io.js/issues/2249 and https://github.com/nodejs/io.js/issues/1104 for more discussion about this problem.

**Comment by jasnell** [comment]
Yeah, I suspected that was the case but hadn't investigated. Unfortunately the documentation is not clear on that at all. I'm going to tag this as a documentation fix. If you're up to it, a PR fixing up the docs is always welcome ;-)

**Comment by jfmercer** [comment]
@targos @jasnell I can have a documentation fix PR ready by Sunday night.
