### ISSUE TITLE
Segmentation fault: EPERM (Operation not permitted) on mmap with both PROT_WRITE and PROT_EXEC

### ISSUE THREAD

**Issue by allanhaywood** [nodejs/node-v0.x-archive#25824]
On kernels that have implemented PaX security, the kernel does not allow an mmap with both PROT_WRITE and PROT_EXEC.

Currently node js does attempt to mmap with both PROT_WRITE and PROT_EXEC in a few places, which prevents node js (in its current implementation) from being used on systems with this more secure kernel.

PaX: https://en.wikipedia.org/wiki/PaX#Restricted_mprotect.28.29

strace:

mprotect(0x6d545e005000, 4096, PROT_NONE) = 0
mmap(0x6d545e006000, 1019904, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = -1 EPERM (Operation not permitted)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x2bf} ---
+++ killed by SIGSEGV +++
Segmentation fault

**Comment by brendanashworth** [comment]
Unfortunately, I don't think this is possible at the current point in time because it is [used by v8 in the JIT compiler](https://github.com/v8/v8/blob/32f13dfbec44dc4882e023c188f4b897bd86ec5c/src/base/platform/platform-linux.cc#L132-L142). This would have to be fixed in v8 and downstreamed to node before this support can happen.

**Comment by allanhaywood** [comment]
Thank you for the follow up, there is a work around on the server side.

Specific applications can be given permissions to Write and Exec mmap, using paxctl.

Here is an example: paxctl -Cm /usr/bin/node
