### ISSUE TITLE
Crypto library's purpose is to provide cryptographically secure APIs yet has an API that specifically states that it is not secure

### ISSUE THREAD

**Issue by dodtsair** [nodejs/node-v0.x-archive#25821]
The crypto library is the place nodejs developers go to when they want to implement cryptographically secure operations.  Yet the pseudoRandomBytes API specifically says that it is not cryptographically secure in the documentation.  I don't see the point of having it in crypto, it seems like a contradiction.  If you get used to using crypto APIs assuming all of the APIs are cryptographically secure then this API is a land mine.  A developer could use it assuming that the pseudoRandom generator used is a cryptographically secure pseudo random number generator.  But it is not.  Thus if they use crypto library for cryptographically securing their communications and accidently use pseudoRandomBytes they actually just created a vulnerability in their web application.  

Aren't cryptographically secure pseudorandom number generators well defined? https://en.wikipedia.org/wiki/Cryptographically_secure_pseudorandom_number_generator.  There are existing algorithms for this that should be easily adopted: Hash_DRBG, HMAC_DRBG

If a developer is okay with a non-cryptographically secure pseudorandom number generator can't they just use Math.random for it?  Why adopt a use case outside the scope of the crypto library?  

I just don't follow the thought process.

**Comment by brendanashworth** [comment]
It was originally, afaik, for when the system didn't have enough entropy to generate secure data. This was changed somewhere along the line to node 4, where node now blocks when the entropy isn't available, and in node 4 `psuedoRandomBytes == randomBytes` because of this. This change won't be backported to node 0.x so I'll close this issue for now. :)

**Comment by bnoordhuis** [comment]
>  A developer could use it assuming that the pseudoRandom generator used is a cryptographically secure pseudo random number generator.

I cannot rightly comprehend the confusion that would make a programmer use something with 'pseudo' in the name for something that should be cryptographically secure.

> If a developer is okay with a non-cryptographically secure pseudorandom number generator can't they just use Math.random for it?

It exists for the same reason why you would use `RAND_pseudo_bytes()` instead of `rand()` in a C program: some applications _prefer_ strong randomness but don't _require_ it to function correctly (like games: predictable game play degrades the experience but doesn't make it unusable.)

When it was added, `Math.random()` was a basic LCG with limited entropy for its initial state and output that was easy to guess on some platforms.

Anyway, like @brendanashworth said, it's been subsumed by `crypto.randomBytes()`.

**Comment by dodtsair** [comment]
Public private key generation uses a a entropy source to seed a CSPRNG.  Part of the point of using a CSPRNG is that you can control how much entropy you consume per byte.   You seed with n bits of entropy and then generate m bytes of pseudo random numbers.  This is process is used in asymmetric key generation because the size of the entropy needed is different than the size of the random bytes needed.

We are not talking games here, they can go and use a RNG or a PRNG and get all the randomness they need.  Cryptographically secure PRNG have specific requirements they must meet:
1. next bit test
2. state compromise extensions

For game developers Nodejs has a math library for PRNG and game developers generally don't need a RNG for entropy
For cryptographic development Nodejs should have a crypto library for CPRNG and CRNG.

Instead you have a crypto library and no one knows that the PRNG is not cryptographically secure.  OpenSSL deprecated their pseudo random number generate for a reason it doesn't meet the first requirement.  But there is still a need for a CPRNG to properly manage your entropy.  

This is standard industry stuff, plenty of documentation.  I consider this to be a severe security vulnerability in Nodejs.  It should be fixed before customers are exploited.  A USCERT should be sent out documententing the vulnerability and providing the steps to fix it.

**Comment by bnoordhuis** [comment]
Sorry, but that's a load of BS.  The v0.10 and v0.12 documentation is very clear about what `crypto.pseudoRandomBytes()` does and doesn't do:

```
## crypto.pseudoRandomBytes(size, [callback])

Generates *non*-cryptographically strong pseudo-random data. The data
returned will be unique if it is sufficiently long, but is not
necessarily unpredictable. For this reason, the output of this
function should never be used where unpredictability is important,
such as in the generation of encryption keys.
```

If you choose to ignore that warning, hey, more fool you.
