### ISSUE TITLE
unicode variable names not working [non-BMP]

### ISSUE THREAD

**Issue by hartsantler** [nodejs/node-v0.x-archive#25854]
type `node` in the terminal, and then paste this into the console:
`var 𝐁=1;`

this becomes:
`var ������ = 1;`

node will not accept the line, and keep printing `...` when the enter key is pressed.

notes:
* this works as it should in google chrome devtools js console.
* i am using Fedora linux

**Comment by KenanY** [comment]
@hartsantler Node.js version?

**Comment by hartsantler** [comment]
version v0.10.36

**Comment by srl295** [comment]
Since it doesn't seem to be a regression (and appears to be the same in
newer nodes) I think we should look at how to fix in the nodejs/node repo
(I linked a bug report).

I'm assuming this is legal ES but I haven't checked the versions yet.  So
still some investigation to do.

Does it work from a .js file?

**Comment by hartsantler** [comment]
i also had problems running it from a .js file that was UTF-16 encoded.

**Comment by srl295** [comment]
@hartsantler are you able to try a UTF-8 encoded .js?

**Comment by srl295** [comment]
We'll track this in https://github.com/nodejs/node/issues/2371
