### ISSUE TITLE
Provide a portable prebuilt Windows zip or tarball download

### ISSUE THREAD

**Issue by pombredanne** [nodejs/node-v0.x-archive#25907]
This exists for Mac and Linux .... But Windows only has either a full MSI or a plain node.exe but no complete zip or tar that contains node and npm and that can be used as-is without having any installer to run.

There used to be an old ticket closed on that topic https://github.com/joyent/node/issues/3978 but things have changed quite a bit since.

I would be happy to help create this kind of archive.

**Comment by pombredanne** [comment]
@orangemocha What would be your take?

**Comment by orangemocha** [comment]
I don't see why we couldn't have an archive with the binaries, npm, include and lib. It would also be useful to be consumed by node-gyp instead of downloading the full source.

Disclaimer: the link at http://imsky.co/notes/nodejs-portable-windows-version-15 is broken and I am not sure what it contained.

@pombredanne : this would be better tracked in https://github.com/nodejs/build/ . Could you open an issue there and close this one?

**Comment by gaurav21r** [comment]
+100 Uninstalling and Installing node / npm on windows leaves artifacts! Frustrating & cause for many complaints in npm
