### ISSUE TITLE
fs.watch and fs.watchFile inconsistencies

### ISSUE THREAD

**Issue by wavded** [nodejs/node-v0.x-archive#5442]
node 0.10.5

`fs.watch('./file')` will return an event emitter which you can listen for a `change` event (this is not documented in the api docs but api matches nice with other repeated events in node core)

`fs.watchFile('./file')` will also return an event emitter that emits the same `change` event but yells at you if you don't provide a `listener` function (fs.watch doesn't yell at cha), so you have to do:

```
var watch = fs.watchFile('./file', function () {})
watch.on('change', function () { })
```

what if:

`change` event was documented and `fs.watchFile` didn't throw a fuss when a listener function was provided to match `fs.watch`

**Comment by PrototypeAlex** [comment]
The documentation has probably changed since you wrote this issue, but looking at the docs now it states fs.watch returns an fs.FSWatcher object, which has two events on it: 'change' and 'error', so that part of your recommendation has been done.

However, it still states that the listener callback in fs.watchFile is not optional, and don't announce that the function returns an event emitter. Which would lead one to assume that providing the callback function is the only way to listen for changes.

**Comment by jasnell** [comment]
@joyent/node-tsc ... any further thoughts on this one?
