### ISSUE TITLE
http client should emit error on content length mismatch

### ISSUE THREAD

**Issue by tjfontaine** [nodejs/node-v0.x-archive#6300]
According to http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html

> When a Content-Length is given in a message where a message-body is allowed, its field value MUST exactly match the number of OCTETs in the message-body. HTTP/1.1 user agents MUST notify the user when an invalid length is received and detected.

We should `emit('error', new ContentLengthError(expected, actual))` or similar.

For too little data we would need to decide if we want to continue to emit the normal `finish`, `end`, `close` sequence, or if it should short circuit.

For too much data it would seem advantageous to allow the user to decide if they want to continue reading or to end the response themselves.

**Comment by mastercactapus** [comment]
I've been debugging a `cb() never called!` issue for near a week now (npm) that seems to stem from this issue when downloading .tgz files during npm installs on a build server.

I've found this issue is also present with **chunked transfer encoding**.


I did a quick check to see how other http client libraries handle protocol violations (Content-Length and Transfer-Encoding) for reference:
```
Curl7.40.0 [CL]: (18) transfer closed with 200 bytes remaining to read
Curl7.40.0 [TE]: (18) transfer closed with outstanding read data remaining
Ruby2.2.1 [CL]: -- didn't complain --
Ruby2.2.1 [TE]: end of file reached (EOFError)
Go1.4.2 [CL]: unexpected EOF
Go1.4.2 [TE]: http: unexpected EOF reading trailer
Wget1.16.3 [CL]: Connection closed at byte 22608. Retrying.
Wget1.16.3 [TE]: -- didn't complain --
Python3.4.2 [CL]: http.client.IncompleteRead: IncompleteRead(22608 bytes read, 200 more expected)
Python3.4.2 [TE]: http.client.IncompleteRead: IncompleteRead(4 bytes read, 4 more expected)
Python2.7.9 [CL]: -- didn't complain --
Python2.7.9 [TE]: httplib.IncompleteRead: IncompleteRead(4 bytes read, 4 more expected)
Node0.10.38 [CL]: --didn't complain --
Node0.10.38 [TE]: --didn't complain --
Node0.12.2 [CL]: --didn't complain --
Node0.12.2 [TE]: --didn't complain --
iojs1.7.1 [CL]: --didn't complain --
iojs1.7.1 [TE]: --didn't complain --
```

There is an undocumented `aborted` event that gets fired that may be of some use in both cases, however I cannot say if handles all cases correctly. Unfortunately nobody seems to be aware/listening for it either so broken connections (even with keep-alive) call back looking successful.

Does anyone know more about this?
