### ISSUE TITLE
Documentation: `fs.createWriteStream` doesn't use `encoding` option

### ISSUE THREAD

**Issue by natevw** [nodejs/node-v0.x-archive#7710]
`fs.createWriteStream` doesn't use the `encoding` option it is documented to have

It does happen to pass it to `stream.Writable` but the streams documentation doesn't imply this would change anything; I'm assuming it's ignored there too. (However, as a side effect, one could pass a `decodeStrings:false` to the `fs.createWriteStream` and that would break the logic in `_write` that assumes `decodeStrings:true`.)

**Comment by chrisneave** [comment]
@natevw I opened a pull request to reference 'defaultEncoding' in the list of default options. I think this is the safer correction as it describes accurately what the code is doing. Perhaps the fs/stream code should be changed to use 'encoding' as the default encoding value instead of defaultEncoding, but this could impact dependent code.

https://github.com/joyent/node/pull/25373
