### ISSUE TITLE
setImmediate callback is not called in child process on Linux

### ISSUE THREAD

**Issue by SevInf** [nodejs/node-v0.x-archive#8040]
We have the following example: https://github.com/SevInf/node-bug-example
On Linux, `setImmediate` callback in child process is never called and  [this text](https://github.com/SevInf/node-bug-example/blob/master/child.js#L3) is never printed. Tested on 0.10.5, 0.10.26, 0.10.28, 0.10.29, 0.11.3.

If we change the [message](https://github.com/SevInf/node-bug-example/blob/master/example.js#L8) sent to a child, for example add/remove field or add few characters to the `text` variable, everything becomes ok and bug does not occur.

**Comment by narqo** [comment]
It seems that that problem is in the size of a data. I had spent some time, experimenting with the topic repo. Looks like timers break if one sent **65533** bytes to the child process.

Here is my [cleaned version of the example from the topic](https://github.com/narqo/node-bug-example).

P.S. The magic 65533 bytes are the size of original `code.txt` from @SevInf example plus the size of serialised JSON data, that is send to the child process.

**Comment by arikon** [comment]
@indutny Could we get fixed this in io.js?

**Comment by narqo** [comment]
@arikon I've tested this with io.js 1.4.1 (in Ubuntu Linux 14.04) and it looks like there is no such problem there. At the same time, the problem still appears with node.js 0.12.0 :(
