### ISSUE TITLE
Windows installer doesn't ensure that $USERNAME\AppData\Roaming exists

### ISSUE THREAD

**Issue by othiym23** [nodejs/node-v0.x-archive#8141]
npm uses `$APPDATA\npm` so that non-Administrator roles have a writable place to stash global packages. Since creating that directory if it doesn't exist _does_ require Administrator privileges, `npm -g install <whatever>` won't / can't work if the base directory doesn't exist (with the correct ACL) before npm is run. The installer should ensure that the whole path is set up at boot time.

Also, either the _documentation_ needs to change, or maybe the _installer_, because right now, people trying to upgrade npm using npm after they've used the .msi frequently end up confused because `npm -g install npm@latest` doesn't actually upgrade them to the newest version of npm, because the first npm on their path is the one that was originally installed alongside node in the Administrator directory. Either the positions of `AppData\roaming\npm` and the Node binary directory need to be swapped in `PATH`, npm should be installed to `AppData\roaming\npm` in the first place, or the documentation should be clarified to tell Windows users exactly how to upgrade npm with the .msi-installed Node.

**Comment by liomry** [comment]
Confirmed today as local Administrator on fresh install of server 2008 RC2. Created folder manually and ran elevated command prompt to work around it

**Comment by aliteralmind** [comment]
" I ran into this same issue doing an installation on Windows 8.1 x64 using node-v0.10.31-x64.msi. For installation, the workaround was to create the $USERNAME\AppData\Roaming\npm directory after installation." ([link](https://github.com/joyent/node/issues/8141#issuecomment-53285314))

Same here.

"It actually turned out the install had simply set the wrong PATH ENVIRONMENT VARIABLE so anything trying to run it wasn't able. It had a trailing slash...once I removed that everything worked fine. Hope that helps someone." ([link](https://github.com/joyent/node/issues/8141#issuecomment-66286021))

My path had ```C:\applications\programming\javascript\nodejs\```. I changed it to ```C:\applications\programming\javascript\nodejs```, relogged in, and it still didn't work.

**Comment by BalaRavilla** [comment]
Try to find this .npmrc file in your user folder in c eg: C:\Users\baravill and make changes there as per the new instillation. Let me know if it works :)

**Comment by teckjon** [comment]
I have followed [https://github.com/npm/npm/wiki/Troubleshooting#error-enoent-stat-cusersuserappdataroamingnpm-on-windows-7](url) for windows 7 installation but I still keep getting error 1909.  I have created the c/users/<user>/appdata/roaming/npm and appdata/npm as other users have suggested.   The installer however keeps rolling back undoing it's installation the moment it hits error 1909.
