### ISSUE TITLE
Error compiling v0.10.31 on Raspberry Pi Model B

### ISSUE THREAD

**Issue by bigorangemachine** [nodejs/node-v0.x-archive#8215]
I think related to: https://github.com/joyent/node/issues/8062

```
/home/pi/node-v0.10.31/out/Release/libopenssl.a(cryptlib.o):cryptlib.c:(.text+0x474): first defined here
/home/pi/node-v0.10.31/out/Release/libopenssl.a(armcap.o): In function `OPENSSL_rdtsc':
armcap.c:(.text+0x44): undefined reference to `_armv7_tick'
/home/pi/node-v0.10.31/out/Release/libopenssl.a(armcap.o): In function `OPENSSL_cpuid_setup':
armcap.c:(.text.startup+0x138): undefined reference to `_armv7_neon_probe'
armcap.c:(.text.startup+0x150): undefined reference to `_armv7_tick'
collect2: ld returned 1 exit status
make[1]: *** [/home/pi/node-v0.10.31/out/Release/node] Error 1
make[1]: Leaving directory `/home/pi/node-v0.10.31/out'
make: *** [node] Error 2
~~~

**Comment by Cydox** [comment]
@nathanjohnson320 how do you compile node? Or what do you patch to make it compile and run?

**Comment by nathanjohnson320** [comment]
They fixed this issue so now you can do:
./configure
make
make install (i use checkinstall instead)

I put the packages on http://node-arm.herokuapp.com/ so you can download them that way if you have Raspbian.

**Comment by brendanashworth** [comment]
I don't know if this is still a pertinent issue, but newer versions compile correctly with raspberry pi (at least node 1.x+), and 0.10 is really far back, patch-wise, and I don't know if we can put many changes to this. Please comment if this is still an issue you'd like to pursue, though — otherwise I'll close this. Thanks for opening the issue!
