### ISSUE TITLE
Crypto library should have a constant-time equality function

### ISSUE THREAD

**Issue by jsha** [nodejs/node-v0.x-archive#8560]
When comparing HMACs, it's important to do a constant-time equality test between two digests to prevent timing attacks. See http://codahale.com/a-lesson-in-timing-attacks/.

According to http://nodejs.org/api/crypto.html, it looks like Node does not currently have a constant-time equality function. One is available as a module at https://www.npmjs.org/package/buffer-equal-constant-time, but this should be a core part of the crypto library since it's essential to correct use of HMACs.

The current library leads to incorrect implementations that use the `==` or `===` operators, such as in this Stack Overflow question and answer: https://stackoverflow.com/questions/10305067/hmac-md5-validation-with-node-js-express-and-trialpay

**Comment by Zolmeister** [comment]
@bnoordhuis 
Your example is unnecessarily complex.
Because you are hashing the value, comparing via `===` is acceptable.

```
 function constTimeEqual(a, b) {
  var ah = crypto.createHash('sha1').update(a).digest('hex');
  var bh = crypto.createHash('sha1').update(b).digest('hex')
  return ah === bh;
}
```

**Comment by sarciszewski** [comment]
@Zolmeister There is a strategy called "Double HMAC" wherein you generate a nonce, HMAC both HMACs with said nonce as the key, then compare them as a normal strategy. It does prevent the leak of meaningful timing information.

The reason "Double HMAC" works is because it uses a random nonce that the attacker cannot predict. If there is ever a RNG failure, this strategy becomes less robust. If there is a break in the hash function, we end up not much better off if we threw caution to the wind and left our code timing attack vulnerable. It's for this reason that most cryptographers employ a true constant-time comparison strategy rather than Double HMAC.

**Your simple hash-based comparison code is like a *broken* Double HMAC strategy.** SHA-1 is a poor choice for a hash function in 2015, for starters.

So, no, the code that @bnoordhuis is not unnecessarily complex. It's the right tool for the job.

**Comment by jsha** [comment]
@sarciszewski: The security of Double HMAC does not depend on the nonce being unpredictable. The security comes from the blinding property. Under Double HMAC the timing no longer indicates any information about the underlying data, and can't be used to guess the data.

The only requirement for Double HMAC is that the nonce not repeat itself very frequently. It would actually be fine to use a non-CS PRNG.

**Comment by sarciszewski** [comment]
> It would actually be fine to use a non-CS PRNG.

Sure, but I wouldn't recommend using a non-CS PRNG if you have a CSPRNG available for any crypto operation, personally.

**Comment by jsha** [comment]
Sorry, I misspoke: It's not even required that the key be a nonce (i.e., not repeat itself). Like in Brad's example, it's fine for the key to be constant. My point was that @Zolmeister's code is not broken. See @hillbrad's earlier detailed comments on the topic.

**Comment by sarciszewski** [comment]
> Like in Brad's example, it's fine for the key to be constant.

No it's not. If you send the same input 10000 times and always get the same output, then your underlying comparison operation is still dangerous. Blinding is helpful, but it doesn't actually remove the fact that some timing information is being leaked. Adding a nonce does achieve this.

**Comment by ircmaxell** [comment]
If we assume that `H()` is a perfect hash function with no pre-image attacks possible (1st or 2nd), then `H(a) == H(b)` does provide timing protection.

However, compared to Double-HMAC (`r` is a random key for each comparison, `Hmac(a, r) == Hmac(b, r)`) and iteration methods (`CRYPTO_memcmp()`), there is an important difference.

All three methods require brute-forcing `b` to find out `a` (they protect `a` in that sense). However, with `H(a) == H(b)`, some of that brute-forcing can happen offline. In fact, the majority of it occurs offline.

Since the comparison is byte-wise, the attacker finds 256 versions of `b` that hash to incrementing first characters (`a`, `b`, `c`... etc). Then timing attack to deduce the first character of `H(a)`. 

From there, the attacker can offline attack `b` to find a new 256 set which has the first character set to what we attacked earlier.

The overall work done is the same in all regards, but in the single-hash version a large portion of it can happen offline in the datacenters of the attacker (on their hardware, using whatever resources they have at their disposal).

How practical this is depends on the possible keyspace of `a`. If `a` is a strongly produced random key >= 128 bits, there's no practical chance of brute-forcing it in any case. But if it's 64 bit, it's definitely within the realm of possibility to be attacked in days in an offline capacity. If it's a low quality "password", it would be trivial to attack this way.

Since there is no real added cost to doing double-hmac verification (pulling a random string and doing 2 more internal hash computations), the additional protection that it gives (especially guarding low-entropy secrets) is important.

**Comment by Zolmeister** [comment]
@ircmaxell 

 > If it's a low quality "password", it would be trivial to attack this way.

Untrue, unless the crpytographic properties of `H()` are compromised.
To generate the 63-bit version of the hash (guessing 1-bit at a time) has no relation to the 64-bit version

**Comment by ircmaxell** [comment]
@Zolmeister I meant in the sense of a dictionary attack. 

Think along these lines:

Assume you go through two rounds and find the first two "hash" characters are `5b`. Then a smart attacker could look at a dictionary of password-sha1 mappings, and see that `sha1("password")` is `5baa61...`. Then they could just try sending `"password"` as the secret.

As far as the 64 bit part, I was more talking about if you knew some information about the source you could start enumerating the 64 bit key server-side, keeping only the guesses which match the prefix you found via timing attacks. So while you're executing the timing attack portion, the cluster could be building up a set of candidate keys that match the currently known key prefix. 

So after deducing a sufficiently large prefix size (say 10 bytes), the number of 64 bit keys that fit the space starts to drop significantly to the point where you can switch from timing attacking the full 20 byte sha1 and instead trying the prefix-filtered permutations.

This style attack requires knowing something about `a`, but that's not out of the realm of possibility either (especially for a framework generic implementation).

**Comment by amingilani** [comment]
+1, atm I need to use a separate module just for this.

**Comment by toejough** [comment]
+1

**Comment by ChALkeR** [comment]
Was reopened as https://github.com/nodejs/node/issues/3043, the discussion should move there.
