### ISSUE TITLE
repl autocomplete broken when output is socket

### ISSUE THREAD

**Issue by smilingthax** [nodejs/node-v0.x-archive#8644]
```
repl.start({
  prompt: 'remote> ',
  input: sock,
  output: sock,  // (replace this with process.stdout and autocomplete works fine)
  terminal: true
});
```

Problem: Tab-autocomplete will only display empty lines. (Tested on 0.10.32 win, 0.10.29 linux).
Workaround:  Set  `sock.columns=80;`

Probable cause:
https://github.com/joyent/node/blob/master/lib/readline.js#L414
  results in  minRows = 0, because maxColumns=Infinity  (via #L382, from #L158)

**Comment by ackalker** [comment]
Yes, i do think it is an issue, for applications which run a node repl as a piped subprocess under their control, for example Emacs comint-mode and the nodejs-repl package, which uses node's completion results to populate its own completion candidates.

In this case, specifying an arbitrary value for `sock.columns` (or `process.stdout.columns` for that matter) needlessly complicates the parsing of the completion results (which need to be transposed into a single column and stripped of whitespace), and it also results in ANSI/VT100 codes being sent when input lines sent to node are longer than the specified number of columns.

From https://github.com/joyent/node/blob/master/lib/readline.js#L382 it appears that the intent was to have `columns == 0` mean: produce a single column of completions, one per line, because nothing else (including `columns == Infinity`!) will let the `|| 1` part get evaluated.

Trying `process.stdout.columns = 0` works in that it doesn't mess with long input lines (no spurious ANSI codes, no wrapping) but currently it suffers from the same problem as not specifying `columns` at all: it just outputs empty lines, no completions.

**Comment by TooTallNate** [comment]
> In this case, specifying an arbitrary value for sock.columns (or process.stdout.columns for that matter) needlessly complicates the parsing of the completion results (which need to be transposed into a single column and stripped of whitespace), and it also results in ANSI/VT100 codes being sent when input lines sent to node are longer than the specified number of columns.

If you're parsing the output programmatically, then you probably want `terminal: false` instead to avoid any VT100 codes from happening.

> From https://github.com/joyent/node/blob/master/lib/readline.js#L382 it appears that the intent was to have columns == 0 mean: produce a single column of completions, one per line, because nothing else (including columns == Infinity, because Math.floor(Infinity / n) still is Infinity!) will let the || 1 part get evaluated.

Agreed that `Infinity` probably isn't the best default value for columns. So do you think `0` is a better default?

> Trying `process.stdout.columns = 0` works in that it doesn't mess with long input lines (no spurious ANSI codes, no wrapping) but currently it suffers from the same problem as not specifying `columns` at all: it just outputs empty lines, no completions.

I think setting `columns` is a mandatory evil. I'd be open to a patch that makes the default behavior better, but ideally your script can notify the node.js server of the dimensions of the "viewport" and set `columns` and `rows` on the socket appropriately.

The telnet protocol offers the ability to send terminal dimensions, including when the user resizes the terminal, so telnet is actually a perfect fit for this use-case. In fact, I wrote a gist that does exactly this a long time ago: https://gist.github.com/TooTallNate/a7017a1dddc543238012

**Comment by ackalker** [comment]
Setting `columns` is not needed because of https://github.com/joyent/node/blob/master/lib/readline.js#L159 , which returns `Infinity` when `columns` from the Interface is undefined or is falsey (better be careful with those `||`s!), or returns its value otherwise.

I've found a very simple fix and have done a little testing, change:
```js
var maxColumns = Math.floor(self.columns / width) || 1;
```
to:
```js
var maxColumns = Math.floor(self.columns / width);
if (maxColumns === Infinity) {
  maxColumns = 1;
}
```

This worked with Tab-completion for `columns=80`, `columns=0` (single column, no input wrapping, yay!) and `columns` undefined.

**Comment by TooTallNate** [comment]
That sounds like it would make the default scenario better. Send a pull request :smile:

**Comment by smilingthax** [comment]
I'd suggest (untested) to change Line 414 from

    var minRows = Math.ceil(group.length / maxColumns);

to

    var minRows = Math.ceil(group.length / maxColumns) || 1;

because the `group.length==0` case has already been dealt with here and `minRows==0` never makes sense here.
This will print all suggestions in a single row -- which is what I would actually expect from `column=Infinity`.

I would expect single column output, for something similar to `columns=0`.
But there is another reason why the `columns`-getter in Line 159 has

   return this.output.columns || Infinity;

Interface.prototype._getDisplayPos (Line 576) will divide by the columns value, and `0` columns does not make sense here (a screen with 0 columns can't display anything...).

But there is still a way to achieve single column output: Consider `self.columns < width`, especially `columns=1`:

    var maxColumns = Math.floor(self.columns / width) || 1;

_will_ fall into the `|| 1` branch -- it's is not superfluous -- and you get single column output (untested).

**Comment by ackalker** [comment]
Thank for your quick reply, I'll have a look at it tomorrow.

**Comment by ackalker** [comment]
@smilingthax 
With regard to leaving `columns === Infinity`, I assume you also want `maxColumns === Infinity`.
Testing your change to `minRows` errors out, because of https://github.com/joyent/node/blob/master/lib/readline.js#L417 .
`idx` gets set to `Infinity` because of `maxColumns === Infinity`, which leads to `item === undefined` which in turn makes `self.output.write(item)` blow up.

**Comment by smilingthax** [comment]
@ackalker
I agree that `maxColumns === Infinity` leads to `idx === Infinity`, which _is_ a problem.

But AFAIUI in this case `if (idx >= group.length) break;` would trigger, and it wouldn't even reach the point where `item===undefined` could blow up.

I think what happens is `idx = Infinity  *  0 + 0`, i.e. `idx === NaN`. Then `break` is not triggered and `item === undefined`, leading to the blow up.

What about:

    if (group.length == 0) {
      return;
    }    
    var minRows = Math.ceil(group.length / maxColumns) || 1;
    var idx = 0;
    for (var row = 0; row < minRows; row++) {
      for (var col = 0; col < maxColumns && idx < group.length; col++, idx++) {
        var item = group[idx];
        self.output.write(item);
        ...
      }
      self.output.write('\r\n');
    }
    self.output.write('\r\n');

**Comment by ackalker** [comment]
@smilingthax 
I've tested your last suggestion: while it does output a single line of completions if `output.columns` is undefined (=> `Infinity`), the output doesn't look very nice. The candidates are interspersed with large chunks of whitespace because of https://github.com/joyent/node/blob/master/lib/readline.js#L424-L426 , the bit of code which with `...` I assume you wish to keep. This also makes it much harder for automation to parse the output (a simple str.split(' ') won't do, lots of empty elements).

Because of this, I'm going to stick with my own suggestion of mapping `maxColumns === Infinity` to `maxColumns = 1`.
IMO it has a much smaller impact because of better locality of changes to the code, it sticks to what I assume is the original intent of https://github.com/joyent/node/blob/master/lib/readline.js#L382 i.e. to have a single column in case `output.columns` cannot be determined with certainty. It also has a more acceptable user experience for users who hack up a quick remote repl on a socket.
