### ISSUE TITLE
setting http.globalAgent.keepAlive does nothing

### ISSUE THREAD

**Issue by andrasq** [nodejs/node-v0.x-archive#9075]
this must be an oversight, but to configure keepAlive in the global agent, `http.globalAgent.options.keepAlive` has to be changed.  The code sets `self.keepAlive` from options, but then later uses `this.options.keepAlive` instead.

See lines 58 and 80 of lib/_http_agent.js in v0.12

**Comment by misterdjules** [comment]
I'm not sure I understand the problem. Could you please paste some code with expected and actual output?

**Comment by andrasq** [comment]
The behavior of http.globalAgent is changed by setting public properties on it.  E.g., `http.globalAgent.maxSockets = 1`

Setting the http.globalAgent.keepAlive property does nothing.  To turn on keepAlive,  `http.globalAgent.options.keepAlive = true` needs to be set.  It should be .keepAlive, not .options.keepAlive.

This is due to an oversight in the code; keepAlive is copied from options but is not subsequently used.  See lines 58 and 80 of lib/_http_agent.js in v0.12 (commit f2b378b850b3bc5ac7e30fb7a204ef19ca4f8604)

Sample code:
```
http = require('http');

function onRequest(res) {
    res.on('data', function(chunk) { console.log(chunk.toString()) });
    res.on('end', makeCalls);
}

ncalls = 10;
function makeCalls( ) {
    options = { host: 'google.com', port: 80, path: '/' };
    if (ncalls-- > 0) http.request(options, onRequest).end();
}

http.globalAgent.keepAlive = true;
makeCalls();
```

Count sockets in TIME_WAIT state before running the test:
`netstat -na | grep TIME_WAIT | wc -lc`
`     9    1520`
Run the test:
`node-v0.12 t.js`
Count sockets in TIME_WAIT after running the test:
`netstat -na | grep TIME_WAIT | wc -lc`
`     19    1520`
Same thing, again:
`node-v0.12 t.js ; netstat -na | grep TIME_WAIT | wc -lc`
`     29    2320`

Expected:  1 socket left unusable in TIME_WAIT
Actual:  10 additional sockets left in TIME_WAIT after each set of 10 http.request calls

Modify the test to set .options.keepAlive instead:  change
```
http.globalAgent.keepAlive = true;
```
to
```
http.globalAgent.options.keepAlive = true;
```
Run the modified test several times, count TIME_WAIT after each run:
`node-v0.12 t.js ; netstat -na | grep TIME_WAIT | wc -lc`
`     10     800`
`node-v0.12 t.js ; netstat -na | grep TIME_WAIT | wc -lc`
`     10     800`
`node-v0.12 t.js ; netstat -na | grep TIME_WAIT | wc -lc`
`     10     800`

Expected: 1 socket left in TIME_WAIT
Actual: 0 additional sockets left in TIME_WAIT

**Comment by mgireesh05** [comment]
With the above test code, I did some experiments and here is what I found on the wireshark dump: 

Test 1
---------
http.globalAgent.keepAlive = true;
Observation: "Connection: keep-alive" header is set by the client, but the client sends a FIN after receiving the response. 
Expected: Client should not send FIN but should keep alive the connection. 

![image](https://cloud.githubusercontent.com/assets/9972525/7878877/a8a8e2e0-0608-11e5-8ac5-d7d7a9cef355.png)

Test 2
---------
http.globalAgent.options.keepAlive = true;
Observation: "Connection: close" header is set by the client, server sends a FIN after sending the response. This is expected behavior.

![image](https://cloud.githubusercontent.com/assets/9972525/7878937/275d63e0-0609-11e5-9d46-c138f4017ae7.png)

Test 3
---------
http.globalAgent.keepAlive = true;
http.globalAgent.options.keepAlive = true;
Observation: "Connection: keep-alive" header is set by the client, and client reuses the connection. Expected behavior, but not sure why both flags need to be set. Ideally 
http.globalAgent.keepAlive = true;
should keep the connection alive. 

![image](https://cloud.githubusercontent.com/assets/9972525/7879031/f42a027a-0609-11e5-8230-c81adc84607f.png)


So it looks like to achieve keep-alive functionality, both flags need to be set to true.

**Comment by chrisskilton** [comment]
Is this still a problem?

**Comment by pkoretic** [comment]
@chrisskilton this is resolved, see https://github.com/nodejs/node/blob/master/lib/_http_agent.js#L84
it is now properly using the keep-alive property set from the options

**Comment by BridgeAR** [comment]
@pkoretic thanks for pointing that out.
