### ISSUE TITLE
Docs: ES6 feature list missing

### ISSUE THREAD

**Issue by gyandeeps** [nodejs/node-v0.x-archive#9170]
I think it would be a good idea to have the list of ES6 feature available for each release.
So that for the consumers of nodejs, its easy to know what they can use and what not.

So far the list for 0.12 version is :
* const
* Maps and WeakMaps
* Sets and WeakSets
* For..of
* Symbol
* Promise

Thanks

**Comment by gtomitsuka** [comment]
Isn't that enough? https://github.com/joyent/node/wiki/ES6-%28a.k.a.-Harmony%29-Features-Implemented-in-V8-and-Available-in-Node

**Comment by gyandeeps** [comment]
Its not the website. That was the point.
Expected: https://iojs.org/en/es6.html

**Comment by misterdjules** [comment]
I agree it would be handy to have a place on the website where developers could easily check what part of the ECMAScript standard they can use.

Today, my understanding is that this is not a priority for the core team because this information is already available somewhere else, like in the Wiki or [elsewhere](http://kangax.github.io/compat-table/es6/#node).
