### ISSUE TITLE
Suppressing 'undefined' in node shell

### ISSUE THREAD

**Issue by tcdaly** [nodejs/node-v0.x-archive#9220]
In the node shell (REPL), I'd like to suppress the output 'undefined' when the output of a command is undefined.

I see there's an option to do this as documented here: http://nodejs.org/api/repl.html

However I don't understand how to activate this option when using the Linux command line (i.e. entering the command 'node' to start the node shell).  Also I don't understand what's meant by 'rlwrap' in the document.

Could anyone help?

**Comment by charlanxcc** [comment]
In order to do that, I think, you need to either modify node.js that's compiled in to node binary or run a small script with ignoreDefault set to true.

1. to run a script with ignoreDefault set to true
<pre>$ node -e "repl = require('repl'); repl.start({igreUndefined: true});"
> var x = 100;
> x
100
</pre>

2. or patch node.js. This way, you can run it like:

<pre>$ NODE_IGNORE_UNDEFINED=1 node
> var x = 100;
> x
100
</pre>

<pre>diff --git a/src/node.js b/src/node.js
index 5046038..e9c5a51 100644
--- a/src/node.js
+++ b/src/node.js
@@ -145,6 +145,9 @@
         if (parseInt(process.env['NODE_DISABLE_COLORS'], 10)) {
           opts.useColors = false;
         }
+        if (parseInt(process.env['NODE_IGNORE_UNDEFINED'], 10)) {
+         opts.ignoreUndefined = true;
+        }
         var repl = Module.requireRepl().start(opts);
         repl.on('exit', function() {
           process.exit();```
</pre>

**Comment by tcdaly** [comment]
Many thanks.  Strangely, answer (1) doesn't work for me - the CLI starts without errors, but still prints 'undefined'.  Could we make adding a new option to the 'node' command (to have the effect of (1)) a feature request for future release?

**Comment by JCK07115** [comment]
I tried method 1, out of curiosity, and found out that if you want to set the value of the boolean that holds the state of an undefined variable, you have to use the actual name of the boolean in the internal of node.js which is "ignoreUndefined." Although for setting it to false, you could refer to the variable as either, "igreUndefined || ignoreUndefined." I attached a screenshot of my findings:

![screen shot 2015-05-03 at 5 28 53 pm](https://cloud.githubusercontent.com/assets/9576322/7447053/856dc6a4-f1ba-11e4-94fb-e97573fdbee1.png)

Also, I thought this meant there might be two variables (properties of repl) that control the state of an undefined variable and so I did a grep search in the directory where this variable is defined in node.js src code. I found nothing for "igreUndefined" but as expected I found 1 result for the actual variable "ignoreUndefined." Again, I attached my findings below:

![screen shot 2015-05-03 at 5 36 30 pm](https://cloud.githubusercontent.com/assets/9576322/7447074/54814e34-f1bb-11e4-8479-20e12064a10c.png)

I had to censor the full path name because it is sensitive info.
